### ISSUE TITLE
Is it possible to build Legato entirely from source?

### ISSUE THREAD

**Issue by yurivict** [legatoproject/legato-af#11]
I am trying to build Legato from source on FreeBSD, but there are components with binaries, like legato-PlatformAdaptor-QmiBin-ar7 and legato-PlatformAdaptor-QmiBin-ar759x. Are they closed source, or source just hasn't been submitted to github?

**Comment by CoRfr** [comment]
Hi yirivict,

Indeed these platform adaptors are closed-source.

**Comment by rianwouters** [comment]
we got the meta-swi-bin content for hfp from swi
since the platformAdaptor libs in legato are also delivered by swi I asked to deliver these as well.
However, have the hfp toolchain build by Yocto, we'd be happy to compile from source ourselves of course :-)
