### ISSUE TITLE
Lock handling API issues with le_updateCtrl_LockProbation and it's counterpart

### ISSUE THREAD

**Issue by JonoJensen** [legatoproject/legato-af#12]
When locking probation using `void le_updateCtrl_LockProbation(void)` this may be ignored according to
> Note: Ignored if the probation period has already ended. 

When the later ignored Lock is unlocked using call to `void le_updateCtrl_UnlockProbation(void)` the system crashes:
`
user.emerg Legato: *EMR* | updateDaemon[455]/updateDaemon T=main | updateCtrl.c DecrementProbationLocks() 194 | Client PID 493 is trying to unset a Probation Lock but never set one.
`

* There's no API to tell if the system is in probation -> cannot conclude if Lock call will fail
* There's no API to tell if a lock is held

Suggestion:
* Allow `le_updateCtrl_LockProbation()` even if system is not yet in probation
* Alternately implement return code to `le_updateCtrl_LockProbation()` that tells if a lock was acquired
* Also implement api to tell if system is in probation (we need this elsewhere but now use heuristics that is not guaranteed to work in future)

**Comment by kdunwoody** [comment]
Is this still an issue?  I think this should be fixed by 9d1e7d5efa1

**Comment by CoRfr** [comment]
There is no release with the fix yet, but it will be in the next release (17.05).

**Comment by JonoJensen** [comment]
Thanks!

And thanks for the pull req. suggestion.
I just hadn't time to prioritize learning how to fix that in the general mayhem at the time, and then I think it got forgotten...

Regards Jon Jensen

--------------------------------------------
Den tors 2017-06-08 skrev Bertrand Roussel <notifications@github.com>:

 Ämne: Re: [legatoproject/legato-af] Lock handling API issues with le_updateCtrl_LockProbation and it's counterpart (#12)
 Till: "legatoproject/legato-af" <legato-af@noreply.github.com>
 Kopia: "JonoJensen" <jono.jensen@yahoo.se>, "Author" <author@noreply.github.com>
 Datum: torsdag 8 juni 2017 16:46
 
 There is no release with the fix
 yet, but it will be in the next release (17.05).
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.
