### ISSUE TITLE
Missing API to detect if system is in probation

### ISSUE THREAD

**Issue by JonoJensen** [legatoproject/legato-af#13]
We lack code to detect if current system is in probation.
We currently rely on this heuristics to work:
```
/**
 * Use reverse engineered heuristics to detect if system is in probation.
 *
 * @return true if system is in probation
 */
static bool estimateSystemInProbation(void)
{
    int32_t curSysIx = le_update_GetCurrentSysIndex();
    int32_t prevSysIx = (curSysIx != -1) ? le_update_GetPreviousSystemIndex(curSysIx) : -1;

    return prevSysIx != -1;
}
```

**Comment by jtchitty** [comment]
Thanks for the report.  This is indeed a missing feature.  Should be easy to add.  Feel like sending us a pull request? :)

**Comment by CoRfr** [comment]
There is a new API in `le_update` (cf https://github.com/legatoproject/legato-af/commit/9d1e7d5efa120485f428c46843ec134c9ff26e99) to get the system state.
It will be in the next release (17.05).
