### ISSUE TITLE
Error launching legato CLI

### ISSUE THREAD

**Issue by aminatamima** [legatoproject/legato-af#14]
Hi all,
I have installed Legato following instructions on Sierra website
https://source.sierrawireless.com/resources/airprime/softwar/legato_application_development_kit_linux/

But when i try to launch the CLI with this command line: 
~/legato$ source ~/legato/packages/legato.sdk.latest/resources/configlegatoenv 
I got the following errors :( : 

Modules:             wp85, wp750x
SDK Path:            /home/<myCUID>/legato/packages/legato.sdk.16.10.1.wp85-wp75-native-x86_64-201702011325
Framework Path:      /home/<myCUID>/legato/packages/legato.framework.16.10.1.wp85-wp750x-201701111029 - $LEGATO_ROOT
Toolchain Path:      /home/<myCUID>/legato/packages/legato.toolchain.1.7.3.SWI9X15Y_07112100-wp85-wp750x-native-x86_64-201701091132 - $WP85_TOOLCHAIN_DIR $WP750X_TOOLCHAIN_DIR
Device Image Path:   /home/<myCUID>/legato/packages/legato.device.image.7.11.22.00.wpX5-201702011120 - $LEGATO_DEVICE_IMAGE
Recovery tools Path: /home/<myCUID>/legato/packages/legato.recovery.4.0.0.linux-201610281311 - $LEGATO_RECOVERY
No toolchain found for target 'ar7'.
Unable to find compatible cross-build toolchain for target 'ar7'.
No toolchain found for target 'ar86'.
Unable to find compatible cross-build toolchain for target 'ar86'.
 
I am following the tuto of mango green with CLI and i am not using a sim card for now. Is it normal to not have response of ping 192.168.2.2 which allow to try to reach my mango card connected to the PC ?

Thank in advance for your help

**Comment by CoRfr** [comment]
Hi!

Which version of firmware do you have?

BTW you can eventually find some support at http://forum.mangoh.io/ since the community is more active over there.

**Comment by aminatamima** [comment]
I am using the WP8548, have anyone already met this kind of error ?
thanks

**Comment by CoRfr** [comment]
What you are seeing from configlegatoenv is just a warning.
`WP85_TOOLCHAIN_DIR` should be defined after, and that is the one that matters.

Your device not answering on 192.168.2.2 is another issue.
- What is your OS?
- Do you have a network interface on your PC that appears when you connect the mangOH? What is the name?
- Also I still don't know the firmware version that you have

**Comment by aminatamima** [comment]
- [ ] I am using linux 16.04

- [ ] Yes i have a network interface, it does not appear when i connect the mangoH but i remind that for now i do not connect a sim card  nor an main antenna to the mangoh, so i dont use a network connectivity. That's why the ping is not working btw

- [ ] Regarding the firmware i can not use the command line tool so i can not check which firmware i am using via "cm info" . Do you know another way to check the firmware version ? I am using legatoo 16.10.1

Thanks

**Comment by seb-sierra** [comment]
Hi @aminatamima , you can try to connect to your mangoh board using a USB/Serial adapter if you have one.
There is a serial port on the mangoh board which gives you a serial console where you can login as root (no password by default). You will be able to run cm info then.

From a terminal, you can use picocom to connect to the serial console (or minicom, screen, cu ...)
`$ picocom -b 115200 /dev/ttyUSBX `
Use the /dev/ttyUSBX corresponding to your USB/Serial adapter, not the TTY port attached from the USB port of the mangoh board
Sometimes, it is easier to find the correct TTY in /dev/seria/by-id/ like 
`$ picocom -b 115200 /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0`

**Comment by aminatamima** [comment]
Thanks @seb-sierra 
I have found the /dev/ttyUSBX corresponding to my USB. This command shows me a "terminal ready" message but it does not respond when i write something (i can not write on it)

I still got the error "toolchain not found". But as @CoRfr said the toolchain not found is a warning, for now i am testing the board ignoring the warning. :)

I am also trying to use the board with windows but according to mangoh.io user guide, it seems like i must have a usb flash drive with specific files to connect the mangoh with the windows PC :( does'nt it ? Please where can i get this files because i do not find them in mangoh.io

Thank you in advance.

**Comment by seb-sierra** [comment]
@aminatamima you may not have write access to the /dev/ttyUSBX, by default Ubuntu/Debian users don't belongs to the dialout group which has the RW access to /dev/ttyUSBX devices.
You need to `sudo adduser <youruser> dialout` and the logout/login from your session or run the picocom command as root (with sudo)

As @CoRfr mentioned, you may find a better support on the mangoh forum: http://forum.mangoh.io/

**Comment by aminatamima** [comment]
@seb-sierra  @CoRfr  Thank you for your answers.
I have found a trail of answers to my questions, I will post them later if everything goes well and close the issue.

Thanks again !

**Comment by aminatamima** [comment]
Ok thanks @seb-sierra 
i have tried both with sudo and add my user to dialout but still can't write on dialout

**Comment by dpfrey** [comment]
@aminatamima: I know this is an old issue, but just in case anyone else comes across it some day...
I think the problem you were having is that after adding a user into a group, the user doesn't gain the group membership until the next time they login.
