### ISSUE TITLE
gnss memory leak

### ISSUE THREAD

**Issue by mzboiu** [legatoproject/legato-af#15]
root@swi-mdm9x15:~# cm info
Device:     WP7502
IMEI:       357851070039529
FSN:        P3704500471010
Firmware:   SWI9X15Y_07.11.22.00 r33729 CARMD-EV-FRMWR1 2017/01/11 18:04:06
Bootloader: SWI9X15Y_07.11.22.00 r33729 CARMD-EV-FRMWR1 2017/01/11 18:04:06
priIdPn:    9906352
priIdRev:   01.04
skuId:      1103114

root@swi-mdm9x15:~# legato version
16.10.3_4fed96ca254facb6f1202a2beb728fd0

root@swi-mdm9x15:~# gnss start
Success!

root@swi-mdm9x15:~# inspect -f --interval=1  pools $(pidof posDaemon) | grep PositionEventDataPoo
         2 |          2 |          2 |          2 |                    2 |       2180 |       4360 | le_pa_gnss.PositionEventDataPoo |            | 
         3 |          3 |          3 |          3 |                    3 |       2180 |       6540 | le_pa_gnss.PositionEventDataPoo |            | 
         5 |          5 |          5 |          5 |                    5 |       2180 |      10900 | le_pa_gnss.PositionEventDataPoo |            | 
         6 |          6 |          6 |          6 |                    6 |       2180 |      13080 | le_pa_gnss.PositionEventDataPoo |            | 
         7 |          7 |          7 |          7 |                    7 |       2180 |      15260 | le_pa_gnss.PositionEventDataPoo |            | 
         8 |          8 |          8 |          8 |                    8 |       2180 |      17440 | le_pa_gnss.PositionEventDataPoo |            | 
         9 |          9 |          9 |          9 |                    9 |       2180 |      19620 | le_pa_gnss.PositionEventDataPoo |            | 
        10 |         10 |         10 |         10 |                   10 |       2180 |      21800 | le_pa_gnss.PositionEventDataPoo |            | 
        11 |         11 |         11 |         11 |                   11 |       2180 |      23980 | le_pa_gnss.PositionEventDataPoo |            | 
        12 |         12 |         12 |         12 |                   12 |       2180 |      26160 | le_pa_gnss.PositionEventDataPoo |            | 
        13 |         13 |         13 |         13 |                   13 |       2180 |      28340 | le_pa_gnss.PositionEventDataPoo |            | 
...
...
...
        63 |         63 |         63 |         63 |                   63 |       2180 |     137340 | le_pa_gnss.PositionEventDataPoo |            | 
        64 |         64 |         64 |         64 |                   64 |       2180 |     139520 | le_pa_gnss.PositionEventDataPoo |            | 
        66 |         66 |         66 |         66 |                   66 |       2180 |     143880 | le_pa_gnss.PositionEventDataPoo |            | 
        67 |         67 |         67 |         67 |                   67 |       2180 |     146060 | le_pa_gnss.PositionEventDataPoo |            | 
        68 |         68 |         68 |         68 |                   68 |       2180 |     148240 | le_pa_gnss.PositionEventDataPoo |            | 
        69 |         69 |         69 |         69 |                   69 |       2180 |     150420 | le_pa_gnss.PositionEventDataPoo |            | 
        70 |         70 |         70 |         70 |                   70 |       2180 |     152600 | le_pa_gnss.PositionEventDataPoo |            | 
        71 |         71 |         71 |         71 |                   71 |       2180 |     154780 | le_pa_gnss.PositionEventDataPoo |            | 
        72 |         72 |         72 |         72 |                   72 |       2180 |     156960 | le_pa_gnss.PositionEventDataPoo |            | 
        73 |         73 |         73 |         73 |                   73 |       2180 |     159140 | le_pa_gnss.PositionEventDataPoo |            | 
        74 |         74 |         74 |         74 |                   74 |       2180 |     161320 | le_pa_gnss.PositionEventDataPoo |            | 
        75 |         75 |         75 |         75 |                   75 |       2180 |     163500 | le_pa_gnss.PositionEventDataPoo |            | 
        76 |         76 |         76 |         76 |                   76 |       2180 |     165680 | le_pa_gnss.PositionEventDataPoo |            | 
        77 |         77 |         77 |         77 |                   77 |       2180 |     167860 | le_pa_gnss.PositionEventDataPoo |            | 
        78 |         78 |         78 |         78 |                   78 |       2180 |     170040 | le_pa_gnss.PositionEventDataPoo |            | 
        79 |         79 |         79 |         79 |                   79 |       2180 |     172220 | le_pa_gnss.PositionEventDataPoo |            | 
        80 |         80 |         80 |         80 |                   80 |       2180 |     174400 | le_pa_gnss.PositionEventDataPoo |            | 
        81 |         81 |         81 |         81 |                   81 |       2180 |     176580 | le_pa_gnss.PositionEventDataPoo |            | 
        82 |         82 |         82 |         82 |                   82 |       2180 |     178760 | le_pa_gnss.PositionEventDataPoo |            | 
        83 |         83 |         83 |         83 |                   83 |       2180 |     180940 | le_pa_gnss.PositionEventDataPoo |            | 
        84 |         84 |         84 |         84 |                   84 |       2180 |     183120 | le_pa_gnss.PositionEventDataPoo |            | 
        85 |         85 |         85 |         85 |                   85 |       2180 |     185300 | le_pa_gnss.PositionEventDataPoo |            | 
        87 |         87 |         87 |         87 |                   87 |       2180 |     189660 | le_pa_gnss.PositionEventDataPoo |            | 
        88 |         88 |         88 |         88 |                   88 |       2180 |     191840 | le_pa_gnss.PositionEventDataPoo |            | 
        89 |         89 |         89 |         89 |                   89 |       2180 |     194020 | le_pa_gnss.PositionEventDataPoo |            | 
...
...
...
    18469 |      18469 |      18469 |      18469 |                18469 |       2180 |   40262420 | le_pa_gnss.PositionEventDataPoo |            | 
     18470 |      18470 |      18470 |      18470 |                18470 |       2180 |   40264600 | le_pa_gnss.PositionEventDataPoo |            | 
     18472 |      18472 |      18472 |      18472 |                18472 |       2180 |   40268960 | le_pa_gnss.PositionEventDataPoo |            | 
     18473 |      18473 |      18473 |      18473 |                18473 |       2180 |   40271140 | le_pa_gnss.PositionEventDataPoo |            | 
     18474 |      18474 |      18474 |      18474 |                18474 |       2180 |   40273320 | le_pa_gnss.PositionEventDataPoo |            | 
     18475 |      18475 |      18475 |      18475 |                18475 |       2180 |   40275500 | le_pa_gnss.PositionEventDataPoo |            | 
     18476 |      18476 |      18476 |      18476 |                18476 |       2180 |   40277680 | le_pa_gnss.PositionEventDataPoo |            | 
     18477 |      18477 |      18477 |      18477 |                18477 |       2180 |   40279860 | le_pa_gnss.PositionEventDataPoo |            | 
     18478 |      18478 |      18478 |      18478 |                18478 |       2180 |   40282040 | le_pa_gnss.PositionEventDataPoo |            | 
     18479 |      18479 |      18479 |      18479 |                18479 |       2180 |   40284220 | le_pa_gnss.PositionEventDataPoo |            | 
     18480 |      18480 |      18480 |      18480 |                18480 |       2180 |   40286400 | le_pa_gnss.PositionEventDataPoo |            | 
[18524.768348] posDaemon invoked oom-killer: gfp_mask=0xd0, order=0, oom_score_adj=0
[18524.774879] posDaemon cpuset=/ mems_allowed=0
[18524.779579] CPU: 0 PID: 621 Comm: posDaemon Not tainted 3.14.29ltsi-a00e464379_b0ce579abb #2
[18524.788186] [<c001583c>] (unwind_backtrace) from [<c00128f0>] (show_stack+0x20/0x24)
[18524.795572] [<c00128f0>] (show_stack) from [<c06158b0>] (dump_stack+0x20/0x28)
[18524.802500] [<c06158b0>] (dump_stack) from [<c0614b30>] (dump_header.isra.14+0x94/0x1dc)
[18524.810924] [<c0614b30>] (dump_header.isra.14) from [<c0102fe0>] (oom_kill_process+0x9c/0x414)
[18524.819408] [<c0102fe0>] (oom_kill_process) from [<c0142924>] (mem_cgroup_oom_synchronize+0x674/0x690)
[18524.828686] [<c0142924>] (mem_cgroup_oom_synchronize) from [<c01038d8>] (pagefault_out_of_memory+0x20/0x6c)
[18524.838514] [<c01038d8>] (pagefault_out_of_memory) from [<c061b8d4>] (do_page_fault+0x33c/0x3fc)
[18524.847182] [<c061b8d4>] (do_page_fault) from [<c00083e0>] (do_DataAbort+0x44/0xa8)
[18524.854812] [<c00083e0>] (do_DataAbort) from [<c0619e78>] (__dabt_usr+0x38/0x40)
[18524.861954] Exception stack(0xcdfc9fb0 to 0xcdfc9ff8)
[18524.867356] 9fa0:                                     b6f17450 00000001 b5680024 00000000
[18524.875352] 9fc0: b5680024 00000001 b6f23fc8 b5680024 b5680170 00000002 00000001 00000001
[18524.883532] 9fe0: 41492cec b567ffc8 4148a290 41489fec 20000010 ffffffff
[18524.889910] Task in /positioningService killed as a result of limit of /positioningService
[18524.898151] memory: usage 40000kB, limit 40000kB, failcnt 123
[18524.904163] memory+swap: usage 0kB, limit 18014398509481983kB, failcnt 0
[18524.910573] kmem: usage 0kB, limit 18014398509481983kB, failcnt 0
[18524.916921] Memory cgroup stats for /positioningService: cache:56KB rss:39944KB rss_huge:0KB mapped_file:56KB writeback:0KB inactive_anon:0KB active_anon:39944KB inactiB
[18524.935386] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[18524.943626] [  509]     0   509    19690    10278      32        0             0 posDaemon
[18524.951500] Memory cgroup out of memory: Kill process 509 (posDaemon) score 1000 or sacrifice child
[18524.960840] Killed process 509 (posDaemon) total-vm:78760kB, anon-rss:39944kB, file-rss:1168kB
Internal error check logs for details.

**Comment by CoRfr** [comment]
That is a known issue that is going to be fixed in 17.05.
The commit is https://github.com/legatoproject/legato-af/commit/b663b4b4af1d3916d3091f9e1d3b6d50438eef98
