### ISSUE TITLE
Trying to make 17.07.1 patch

### ISSUE THREAD

**Issue by virajpadte** [legatoproject/legato-af#17]
I am trying to perform a make wp85 on the 17.07.1 release. Facing the following error:

ninja  -f /home/jarvis/legato-17.07.1/build/wp85/framework/build.ninja
[2/50] Compiling liblegato source file
FAILED: /gcc -MMD -MF /home/jarvis/legato-17.07.1/build/wp85/framework/obj/args.c.o.d -g -c /home/jarvis/legato-17.07.1/framework/c/src/args.c -o /home/jarvis/legato-17.07.1/build/wp85/framework/obj/args.c.o -Wall -fPIC -Werror -O2 -DLE_COMPONENT_NAME=framework -I/home/jarvis/legato-17.07.1/framework/c/inc -DDISABLE_SMACK=0 -DLE_SVCDIR_SERVER_SOCKET_NAME="\"/tmp/legato/serviceDirectoryServer\"" -DLE_SVCDIR_CLIENT_SOCKET_NAME="\"/tmp/legato/serviceDirectoryClient\"" -DLEGATO_EMBEDDED
/bin/sh: 1: /gcc: not found
[2/50] Compiling liblegato source file
FAILED: /gcc -MMD -MF /home/jarvis/legato-17.07.1/build/wp85/framework/obj/addr.c.o.d -g -c /home/jarvis/legato-17.07.1/framework/c/src/addr.c -o /home/jarvis/legato-17.07.1/build/wp85/framework/obj/addr.c.o -Wall -fPIC -Werror -O2 -DLE_COMPONENT_NAME=framework -I/home/jarvis/legato-17.07.1/framework/c/inc -DDISABLE_SMACK=0 -DLE_SVCDIR_SERVER_SOCKET_NAME="\"/tmp/legato/serviceDirectoryServer\"" -DLE_SVCDIR_CLIENT_SOCKET_NAME="\"/tmp/legato/serviceDirectoryClient\"" -DLEGATO_EMBEDDED
/bin/sh: 1: /gcc: not found
ninja: build stopped: subcommand failed.
Makefile.framework:108: recipe for target 'liblegato' failed
make[1]: *** [liblegato] Error 1
make[1]: Leaving directory '/home/jarvis/legato-17.07.1'
Makefile:254: recipe for target 'framework_wp85' failed
make: *** [framework_wp85] Error 2

**Comment by CoRfr** [comment]
Hi @virajpadte,

Did you download and install the wp85 toolchain from source.sierrawireless.com or in Dev Studio?

**Comment by virajpadte** [comment]
That solved the problem thanks! There was some problem while setting up the environment variable WP85_TOOLCHAIN_PREFIX. There is a typo in README.md ~~arm-poky-linux-gnuabi-~~ arm-poky-linux-gnueabi-
