### ISSUE TITLE
/dev/nmea - bad select()/read() behaviour if GNSS engine is stopped

### ISSUE THREAD

**Issue by obiltschnig** [legatoproject/legato-af#18]
Context: I'm using `/dev/nmea` to read the raw GNSS NMEA stream and process it myself. 

Before the calling `read()`, I'm calling `select()` to check if any data is available, and to prevent `read()` from blocking if no data is available.

Everything works fine if the GNSS engine has been started (`$ gnss start`).

However, if the GNSS engine is not running, then `select()` reports that data is available, but `read()` blocks until I start the GNSS engine again.

So the issue is that `select()` should not mark the file descriptor as readable when the GNSS engine is not running and there's nothing to read.

Legato version is 16.10.1_a6a25fbda05738774857dccb9fd76a99 on a WP8548 (MangOH Green).

**Comment by obiltschnig** [comment]
Addition: read() also blocks in the above case if I set the file descriptor to non-blocking.

**Comment by CoRfr** [comment]
Hi @obiltschnig,

have you tried to reproduce the issue with a more recent version of Legato, such as 17.07.2 with WP85 Release 14?

**Comment by obiltschnig** [comment]
Not yet, but can try in the next couple of weeks.

**Comment by CoRfr** [comment]
Stall issue, please reopen if that's still a problem.

Thanks!
