### ISSUE TITLE
ifgen - UnpackOutputs uses wrong message reference for api type 'file' parameter

### ISSUE THREAD

**Issue by raffaeleau** [legatoproject/legato-af#19]
**Context:** 
Since moving to Legato 17.07.1 from 16.10.3, apps using Legato's IDL `file` type to pass an open file descriptor from a server to a client will always give a value of -1.
- `file fd OUT` will always set the fd pointer to -1
- `file fd IN` works correctly

See forum topic at - http://forum.legato.io/t/legato-idl-pre-defined-type-file-not-working-with-legato-17-07-x/2664/5

**Problem:**
The auto-generated client code by `ifgen` uses a reference to the request message (`_msgRef`) rather than a reference to the response message (`_responseMsgRef`) when unpacking the output `file` parameter.

**Solution:**
In _legato/framework/tools/ifgen/langC/templates/pack.templ_, at line 180, change `_msgRef` to `_responseMsgRef`.
```
178 |    if ({{parameter|FormatParameterName}})
179 |    {
180 |        *{{parameter|FormatParameterName}} = le_msg_GetFd(_responseMsgRef);
181 |    }
```

**Comment by CoRfr** [comment]
Solved by https://github.com/legatoproject/legato-af/commit/2a4a02d1e0b2eb988611ad226bf56134f27f5aa0
