### ISSUE TITLE
SetProcUidGid fails if user and group already exist

### ISSUE THREAD

**Issue by tegoo** [legatoproject/legato-af#2]
1. mkapp
2. instapp
3. `updateDaemon.c -> le_update_Create -> SetProcUidGid(SECURITY_UNPACK_USER)`

In SetProcUidGid routine implementation  after 
`LE_FATAL_IF(user_Create(usrID, &uid, &gid) == LE_FAULT, "Can't create user: %s", usrID);
`
uid and gid remain undefined as SecurityUnpack user is already exists. As a result 
`LE_FATAL_IF(setgid(gid) == -1, "Could not set the group ID.  %m.");`
gives an error:
`updateDaemon.c SetProcUidGid() 368 | Could not set the group ID.  Invalid argument.`.

**Comment by bcmitchells** [comment]
Hi Vladimir. Good catch! We have actually fixed this one - it'll be pushed next week with a bunch of other new stuff. Thanks for helping out!

**Comment by bcmitchells** [comment]
Fix is now published.

**Comment by tegoo** [comment]
Thanks!
