### ISSUE TITLE
Make Fail

### ISSUE THREAD

**Issue by Shrunoti** [legatoproject/legato-af#29]
I tried to run make in the legato folder:

****ERROR: Unrecognized target type 'dir'.
No toolchain found for target 'dir'.
****ERROR: Unrecognized target type 'prefix'.
No toolchain found for target 'prefix'.
Module: WiFi
Module: Dualsys
make localhost
make[1]: Entering directory '/home/shrunoti/Downloads/workspace/legato'
Module: WiFi
Module: Dualsys
make -f Makefile.hostTools
make[2]: Entering directory '/home/shrunoti/Downloads/workspace/legato'
Using ninja installed at: ***ERROR: Ninja build tool not found.
Makefile.hostTools:52: recipe for target 'ninja' failed
make[2]: *** [ninja] Error 1
make[2]: Leaving directory '/home/shrunoti/Downloads/workspace/legato'
Makefile:266: recipe for target 'tools' failed
make[1]: *** [tools] Error 2
make[1]: Leaving directory '/home/shrunoti/Downloads/workspace/legato'
Makefile:49: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by Shrunoti** [comment]
I tried sudo make  and it worked.

**Comment by CoRfr** [comment]
Weird, it looks like ninja might not be installed?
```
Makefile.hostTools:52: recipe for target 'ninja' failed
```
I'm surprised that with `sudo` it works.
Did you install the software required as mentioned in https://github.com/legatoproject/legato-af#dependencies ?
