### ISSUE TITLE
keyword in API

### ISSUE THREAD

**Issue by tatraian** [legatoproject/legato-af#30]
Hello,

I tried to create an AirVantage application in C++. But unfortunately the current API interface is not compatible (as far as I see) with c++. The ```le_avdata_SetNamespace``` calls its variable as ```namespace``` that is a keyword in C++. So this API cannot be used in C++. Could you rename the variable? As I think this doesn't breaks the API.

Thanks!

**Comment by tatraian** [comment]
I created a pull request for this: #31 
I'm not really know how the ```c``` files and ```api``` files are connected, but that worked for me...

**Comment by CoRfr** [comment]
Should be addressed by: 
- mkTools keywords mangling: https://github.com/legatoproject/legato-af/commit/d3803ba46e57ccfe22a3b47d4e5750ea9c280aae
- UT: https://github.com/legatoproject/legato-af/commit/1df4f30ad082c56bd65d64925ddcc9c80aaa4682
