### ISSUE TITLE
Confusion about installation

### ISSUE THREAD

**Issue by komalpharate** [legatoproject/legato-af#33]
It is mentioned that:-

    Clone the environment:

$ mkdir workspace
$ cd workspace
$ repo init -u git://github.com/legatoproject/manifest
$ repo sync

You can also clone a specific release:

$ repo init -u git://github.com/legatoproject/manifest -m legato/releases/16.07.0.xml
$ repo sync

Install the Legato framework on your development PC

    Clone it from GitHub or untar a release archive into a directory

    cd into that directory

    Run make
----------------------------------------------------------------
repo sync in workspace results in download of legato folder
then again I have to clone legato-af folder?

how different are they?
also make fails if I clone legato-af 
which works in legato folder

**Comment by CoRfr** [comment]
You shouldn't have to clone twice.
What the README.md tries to say is:
- Clone from GitHub (using repo) or extract a release tarball
- cd into that directory (so `cd legato` typically)

**Comment by komalpharate** [comment]
Okay.
Clone from GitHub (using repo) doesnt seem to contain platformAdapter etc folders.
And give make errors because of that

**Comment by komalpharate** [comment]
Also
Scenario:
Currently the mangOH board is'nt with me.
I want to run legato sample apps locally.
Do I still need tollchain?
What are the steps I should follow?
I tried doing
`mkapp -t localhost httpGet.adef`
It gives error 

** ERROR:
/home/komal/workspace/legato/apps/sample/httpGet/httpGetComponent/Component.cdef:15:8: error: Can't find dependent .api file: 'le_mdc.api'.

It was working previously but I again tried to setup the legato and getting this issue.

**Comment by CoRfr** [comment]
The clone from GitHub with `git clone` wouldn't provide the platformAdapters, but with `repo` it should

You would still need the toolchain to build for wp85, but if you just build for localhost there is no need for a particular toolchain, however you wouldn't be able to run the sample apps locally as `localhost` target can't run apps.

**Comment by komalpharate** [comment]
Thank you.
I expected it will work as helloWorld app works locally.
Also if the mangOH wp76x board is with legato 17, then legato 18 apps won't work on that right?
If so, Can you you help me to know how to upgrade it to 18?

**Comment by CoRfr** [comment]
There would likely be some compatibility issues, so it's best to have the apps in sync with the framework.

There are few good guides on mangoh.io to upgrade: http://mangoh.io/uploaded-documents/Reference/mangOH%20Red/Discover/Getting%20Started/mangOH%20Red%20GSG%20-%20Linux%20R2/#t=41112261_mangOH_Red_GSG_-_HTML5%2F41112261_UpLegato%2F41112261_UpLegato.htm
