### ISSUE TITLE
Typo in voice call docs.

### ISSUE THREAD

**Issue by robertselberg** [legatoproject/legato-af#34]
There is a small typo in this document: https://docs.legato.io/latest/c_le_voicecall.html

This part is wrong:

"If le_voicecall_End() failed a LE_VOICECALL_EVENT_END_FAILED event will be sent. If le_voicecall_Answer() failed a LE_VOICECALL_EVENT_ANSWER_FAILED event will be sent."

This word should be replaced: LE_VOICECALL_EVENT_ANSWER_FAILED

With this word: LE_VOICECALL_EVENT_CALL_ANSWER_FAILED

**Comment by CoRfr** [comment]
Thanks for the heads up @robertselberg , will fix that right away.

**Comment by CoRfr** [comment]
Fixed in https://github.com/legatoproject/legato-af/commit/f02e077dd7af16e28aecfe40d564b2f5af7b564b
