### ISSUE TITLE
Voice call service can't handle a crashed application.

### ISSUE THREAD

**Issue by robertselberg** [legatoproject/legato-af#35]
The voice call service starts to misbehave I don't terminate a call the correct way.

1. I start an application that makes a phone call to my cell phone.
2. I answer the call.
3. I stop the app using "app stop <application>"
4. I terminate the call using my cell phone.
5. When start the application again and try to make another call I get this:

May 28 09:46:11 | voiceCallService[8606]/voiceCallService T=main | voiceCallServiceServer.c le_voicecall_Start() 647 | New profile can't be allocated

I think this is a bug in the voice call service, since it should be able to handle crashing applications without breaking its own functionality.

**Comment by CoRfr** [comment]
Hi @robertselberg ,

Looks like it would be an issue at the service level, but could you give some more info about the versions and device that you are using?

Thanks!

**Comment by robertselberg** [comment]
mangoh green, wp76, legato 18.03.0.

**Comment by CoRfr** [comment]
Should be fixed since 18.07.0 by https://github.com/legatoproject/legato-af/commit/2f409a1779f208c333082089908457789c72f847
