### ISSUE TITLE
Why the CheckUnsolicited() function was removed ?

### ISSUE THREAD

**Issue by EduardShaid** [legatoproject/legato-af#37]
Why the **CheckUnsolicited**() function was removed from inside SendingState (case EVENT_PROCESSLINE) ?

file "le_atClient.c"

**Comment by CoRfr** [comment]
@EduardShaid , as far as I can tell this code was always commented out.

Did you notice a bug in particular?

**Comment by adoussain** [comment]
@EduardShaid, the case EVENT_PROCESSLINE treats an ongoing AT command. Unsolicited handling is not very clear on that point into the V25-te (see 5.8.2) recommendation. Unsol could be sent, suppressed, deferred when a modem needs to send it during an AT command processing. This mainly depends on the modem behavior, not from Legato.

We choose the option that the modem deferred the unsolicited (it means the modem sends the unsol after the final response of a command), and so we don't need to check for unsolicited when an AT command is ongoing.
