### ISSUE TITLE
Bug in liblegato/linux/args.c : le_arg_GetIntOption()

### ISSUE THREAD

**Issue by driverific** [legatoproject/legato-af#38]
In this fn., GetOptionValue returns a pointer to the value (valuePtr) but then le_utf8_ParseInt is called with Argv[index + 1] instead of valuePtr.  As a result, it works for short-form options but fails for long-form options.

**Comment by CoRfr** [comment]
Thanks @driverific , will have a look!

**Comment by CoRfr** [comment]
We fixed this issue in https://github.com/legatoproject/legato-af/commit/7e9817ea60c17971ff9a839665e9be7a92ce936d
