### ISSUE TITLE
Component definition content deleted when creating .c file

### ISSUE THREAD

**Issue by langestefan** [legatoproject/legato-af#41]
Hi,

When adding a source file in developer studio sometimes the contents of the .cdef file are removed but the file is still present. This makes it impossible to compile the project, resulting in the following error:

`** ERROR:
/home/mangoh/MangOHdevelopment_git/dev/dev/<exe>/<exe>.adef:9:4: error: Executable doesn't contain any components that have source code files.
Makefile:37: recipe for target 'target' failed`

This is done by going to developer studio --> right click project --> new --> source file. Placing back the content manually fixes the issue until it happens again.

**Comment by langestefan** [comment]
Hi @CoRfr 

I am using Developer Studio 5.3.1.

**Comment by sarraly** [comment]
Hello,

Developer Studio is a very old product that has run it's course and at this time we are not making any further changes to the code base.  

Our new IDE tool is a Legato Plug-in for Visual Studio Code and we're going to be publishing how to move over from Developer Studio to VSCode very shortly.  

The getting started information for using Legato with VSCode is here: https://docs.legato.io/latest/tools_vsCode.html

If you need any help or have any questions please feel free to post them in our forum: http://forum.legato.io 

Thank you
