### ISSUE TITLE
Kconfiglib tip re. preprocessor

### ISSUE THREAD

**Issue by ulfalizer** [legatoproject/legato-af#42]
Hello,

There's an often overlooked feature re. the preprocessor support in Kconfiglib that might be handy in your case: Preprocessor functions can be defined in Python.

If you drop a module named `kconfigfunctions.py` with the following contents somewhere where it can be imported by Kconfiglib (might have to tweak `PYTHONPATH`), you'll get Python versions of `b2k` and `empty`, for example:

```python
def b2k(kconf, _, val):
    return "y" if val in {"1", "y"} else "n"


def empty(kconf, _, val):
    return "y" if not val else "n"


functions = {
    "b2k":   (b2k,   1, 1),
    "empty": (empty, 1, 1),
}
```

This saves having to start a bunch of shell processes, makes the functions portable (if you need that), and also means you'll get an error if you pass the wrong number of arguments.

See the `Preprocessor user functions defined in Python` section in the Kconfiglib docstring for more details.

Cheers,
Kconfiglib guy

**Comment by CoRfr** [comment]
Hey @ulfalizer ,

Thanks for your advice and your great work regarding Kconfiglib.
I've notified the developer that takes care of that and we'll have a look!

**Comment by ulfalizer** [comment]
Thanks!

No great hurry. Might save some pain down the line though.
