### ISSUE TITLE
Issues building 19.05 for wp77xx

### ISSUE THREAD

**Issue by akankshaashwini** [legatoproject/legato-af#44]
I am trying to build legato 19.05 for wp77xx and I get the following errors:
> Building Legato for target 'wp77xx'
> Makefile:127: build/wp77xx/.config.mk: No such file or directory
> KSET     ~workspace/legato/.config.wp77xx - TARGET_WP77XX
> Traceback (most recent call last):
> File "~/workspace/legato/3rdParty/Kconfiglib/setconfig.py", line 20, in <module>
    import argparse
> ImportError: No module named 'argparse'
> Makefile:382: recipe for target '~/workspace/legato/.config.wp77xx' failed
> make: *** [~/workspace/legato/.config.wp77xx] Error 1

- I am trying to use 19.05 because, with 19.04 ulpm api doesn't seem to work and portDaemon is restarting all the time (https://forum.legato.io/t/portdaemon-constantly-restarts-in-19-04-0/4488). 

Any help will be appreciated.

**Comment by CoRfr** [comment]
Hi @akankshaashwini ,

can you try installing {{python-argparse}} ? It seems missing.

**Comment by CoRfr** [comment]
I'm going to close this ticket has there was no reply and it seems that installing `python-argparse` would be enough to solve the issue.
