### ISSUE TITLE
legato-af / framework / c / src / thread.c - error code incorrectly fetched

### ISSUE THREAD

**Issue by JonoJensen** [legatoproject/legato-af#6]
Hi
I think in thread.c error code is read from errno but is probably returned as return arg.
Line=817
 
811     int result = pthread_create(&(threadPtr->threadHandle), 
812                                 &(threadPtr->attr), 
813                                 PThreadStartRoutine, 
814                                 threadPtr); 
815     if (result != 0) 
816     { 
817         int err = errno;      **<<<--- Error here**
818         LE_EMERG("pthread_create() failed with error code %d (%m).", err); 

Example from man:
#define handle_error_en(en, msg) \
               do { **errno = en;** perror(msg); exit(EXIT_FAILURE); } while (0)
               s = pthread_create(&tinfo[tnum].thread_id, &attr,
                                  &thread_start, &tinfo[tnum]);
               if (s != 0)
                   handle_error_en(s, "pthread_create");

**Comment by JonoJensen** [comment]
Seems also be a build issue with target wp85 from 16.04.1 to head
`make wp85`
gives
```
mksys -t wp85 -w build/wp85/system -o build/wp85 system.sdef \
                        -C "-DPCM_IF="AUX"" -C "-DI2S_IF="PRI"" -C "-DUSB_IF="AFE_PCM"" -C "-DCODEC_IF="PRI""
** ERROR:
/home/repper/legato16.01/legato-af/components/airVantage/avcDaemon/Component.cdef:36:8: error: Couldn't find component '/home/repper/legato16.01/legato-af/platformAdaptor/qmi/bin/wp85/components/le_pa_avc'.
make: *** [system_wp85] Error 1
```

**Comment by CoRfr** [comment]
Hi Jono,

for the build issue please refer to the README.md, as the development has now switched to repo.

For the bug looks like errno is not managed by pthread functions, which would explain why there is that macro in the `man pthread_create`:

`       #define handle_error_en(en, msg) \
               do { errno = en; perror(msg); exit(EXIT_FAILURE); } while (0)`

**Comment by jtchitty** [comment]
Agreed.  This is a bug.

Should change to `errno = result` and also get rid of the '%d' and the ', err' in the error message.
