### ISSUE TITLE
Legato forum staff is bigoted

### ISSUE THREAD

**Issue by jasp00** [legatoproject/legato-af#60]
I have read your code of conduct, I agree with it, and I do not care if you remove this issue.

You pledge to make participation in your community a harassment-free experience for everyone; except for me. I signed up for your forum and tried to help one of your users, who is also on GitHub, in the most respectful way. Then you banned me without any explanation.

I will certainly not contribute to your project. Have a good life.

**Comment by thibs0** [comment]
Dear Javier,

From what I understand, you've been banned from the forum after having used it as a way to hassle another forum user in public and after having been flagged by several people in the community who felt your post as innapropriate.

I've looked for your post and found it (id: 5328, created_at: 2020-08-01 00:15:33 UTC). Here's my analysis:
* it was not helping anyone on a technical stand point, as you're claiming
* your post was not related to Legato, and was even not a technical subject at all
* your post was disrespectful for another person, that you referenced in your post. It actually was the only purpose of your post (to contact this person).
* your post gave sensitive information on this person and his relationship with you, without his consent.

I hope you understand that it is innapropriate to use a public forum for contacting in public someone who doesn't want to be contacted by you in any way, like by phone, as you wrote yourself it in your post. To me, the decision for banning you taken by the moderator was appropriate.

Kind regards

.Thibault.
Director, Developer Program

**Comment by jasp00** [comment]
>    * it was not helping anyone on a technical stand point, as you're claiming

I did not claim to help the user on a technical standpoint; you are the liar.

>    * your post was not related to Legato, and was even not a technical subject at all

This is the problem with open-source projects compared to free-software ones: you do not care about people. So what if it was not a technical subject? If I can help a Legato user, then it is related to Legato. Of course, your bigotry does not let you understand this.

>    * your post was disrespectful for another person, that you referenced in your post. It actually was the only purpose of your post (to contact this person).

What content from my post was disrespectful? Did I insult the user? Did I say she was a liar and a bigot like I am calling you? Or did I say that I was proud of her success?

>    * your post gave sensitive information on this person and his relationship with you, without his consent.

What sensitive information did I reveal? Real name? Postal address? Email address? Cellphone number? Twitter account? Of course I talked about our relationship. How else could I help her with her problem?

> it is innapropriate to use a public forum for contacting in public someone who doesn't want to be contacted by you in any way, like by phone, as you wrote yourself it in your post.

What do you know about our communications? How do you know that she did not want to be contacted by me in any way? I only wrote "Since you refused to communicate by phone yesterday". Your action comes from prejudice.

> To me, the decision for banning you taken by the moderator was appropriate.

Of course, you think so because you are bigoted. You could have clarified your community guidelines. You could have told me: "Please discuss only technical matters in this forum." Instead, you banned me without any explanation. Thus, expect no technical contribution from me.

I will not interact with you any longer in this thread. However, I warn you: we are not on your realm, but on GitHub. If you insist on slandering me, I may take action.
