### ISSUE TITLE
Continuous eCall redialing

### ISSUE THREAD

**Issue by adrianalin** [legatoproject/legato-af#62]
Hello,

I am having a problem running the apps/sample/eCallDemo application, on ar86 platform. 

I trigger an eCall but after I hangup the call from my phone, it gets triggered back again. When hanging up I get the LE_ECALL_STATE_DISCONNECTED (with reason 55, LE_MCC_TERM_UNDEFINED), and the state goes automatically to LE_ECALL_STATE_STARTED, and redialing happens.

There is any specific reason why this redialing happens?

**Comment by jberdin** [comment]
Hi,

Could you provide some details about the software versions you are using?

cm info
legato version
cat /etc/legato/version
cat /proc/version

**Comment by adrianalin** [comment]
I can say that legato version we use is 16.01.0.m4.rc2
