### ISSUE TITLE
Priority obo between .adef and code in thread.c.h & le_thread.h

### ISSUE THREAD

**Issue by JonoJensen** [legatoproject/legato-af#7]
We cant set workerthread prio to _RT_1 when .adef sets pid to "priority: rt1". 
This seems to be due to an offset 1 between the two definitions.
In order to get this to work we ned to set rt2 in .adef which matches _RT_1 in le_thread.h.
See terminal log below.

.adef,priority:rt1  => RR 41
.adef,priority:rt2  => RR 42
code _RT_1 => RR42            **<--- Should probably be RR 41**

I.e. there seems to be an offset bug in the iterpretation of le_thread_Priority_t in le_thread_SetPriority(,) line 678 `struct sched_param param = {.sched_priority = priority};`

/Jon & Per Å

---
root@permocell:~# ulimit -r
0
root@permocell:~# ulimit -r unlimited   **<--- Make test work**
root@permocell:~# ulimit -r
unlimited
root@permocell:~# legato start
Starting Legato...

** .adef=rt1, no prio change in code:**

```
root@permocell:~# ps axm --format uname,pid,ppid,tty,cmd,cls,pri,rtprio | grep -A 2 -E 'spihandler|COMMAND'
1016      5413  5375 ?        spihandler                    -   -      -
1016         -     - -        -                            RR  41      1
1016         -     - -        -                            TS  19      -
--
root      6332  4969 pts/0    grep -A 2 -E spihandler|COM   -   -      -
root         -     - -        -                            TS  19      -
root@permocell:~#
```
** .adef=rt2, prio change to LE_THREAD_PRIORITY_RT_1**

```
root@permocell:~#  ps axm --format uname,pid,ppid,tty,cmd,cls,pri,rtprio | grep -A 2 -E 'spihandler|COMMAND'
1014      1551   992 ?        spihandler                    -   -      -
1014         -     - -        -                            RR  42      2
1014         -     - -        -                            RR  42      2
```

**Comment by CoRfr** [comment]
Hi @JonoJensen,

could you please check that https://github.com/legatoproject/legato-af/commit/79f0216c645345e24edc6201b8ce756af7466452 fixes this issue ?

Thanks
Bertrand

**Comment by JonoJensen** [comment]
Hi, I'm currently on vacation and as I remember per å is also. Thus I have no easy way of checking this for a few weeks. 
Me or Per å will check it first thing when we are back.  I'll try to check the diff on my phone when not in the rollacosters! We've got "skip the line" tickets for tomorrow!!
Regards Jon 
Skickat från Yahoo Mail på Android 
 
  Den tors, juli 2016 klockan 21:53, Bertrand Roussel<notifications@github.com> skrev:   
Hi @JonoJensen,

could you please check that 79f0216 fixes this issue ?

Thanks
Bertrand

**Comment by JonoJensen** [comment]
Hi,
Sorry fot the late answer. We've been realy bussy on our side. Now we've switched to le16.07 and i updated manifest to rr1 and tried out your fix.
It works perfectly!
Thanks /Jon
