### ISSUE TITLE
Minor: Missing newline in output from "update"

### ISSUE THREAD

**Issue by JonoJensen** [legatoproject/legato-af#9]
Seems to be a missing newline in update command:
`
root@permocell:~# update --mark-good
System is now marked 'Good'root@permocell:~#  
`

Should be \n after 'Good'.

**Comment by CoRfr** [comment]
Should be good now !

If you want in the future you can eventually resolve these issues by providing Pull requests, there is some info about how to contribute here: http://legato.io/legato-docs/latest/aboutLegatoContributing.html .
